AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for Kittens Carousel Static Website on EC2. This template deploys Kittens Carousel Static Website on Amazon Linux 2 EC2 Instance with custom security group allowing http connections on port 80. Kittens Carousel Static Website is downloaded from GitHub repository, then deployed on Apache Web Server.

Resources:
  WebServerSecurityGroup:
  Type: "AWS::EC2::SecurityGroup"
  Properties:
    GroupDescription: Enable HTTP for Apache Web Server and ssh for terminal
    SecurityGroupIngress:
      - IpProtocol: tcp 
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
    Tags:
      Key: 
      Value: My first Security Group from Cloudformation
WebserverHost:
  Type: "AWS::EC2::Instance"
  Properties:
    ImageId: ami-08e4e35cccc6189f4
    InstanceType: t2.micro
    KeyName : elifec2
    SecurityGroupIds: 
      - !Ref WebServerSecurityGroup
    Tags: 
      - Key: Name
        Value: !Sub Web Server of ${AWS::StackName} Stack 
    UserData: 
      Fn::Base64:
        !Sub |
          #! /bin/bash
          yum update -y
          yum install httpd -y
          cd /var/www/html/
          wget https://raw.githubusercontent.com/eliferdemdevops/static-web-kitten/main/index.html
          wget https://raw.githubusercontent.com/eliferdemdevops/static-web-kitten/main/cat0.jpg
          wget https://raw.githubusercontent.com/eliferdemdevops/static-web-kitten/main/cat1.jpg
          wget https://raw.githubusercontent.com/eliferdemdevops/static-web-kitten/main/cat2.jpg
          systemctl start httpd
          systemctl enable httpd
    
Outputs:
  WebsiteURL:
    Value: !Sub
      -  http://${PublicAddress}
      -  PublicAddress: !GetAtt WebserverHost.PublicDnsName
    Description: Kittens Carousel Application URL